LearningShare/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url, include
from django.views.generic import RedirectView
from tree.views import create
from . import settings
from django.views.static import serve

urlpatterns = [
    path('', RedirectView.as_view(url='question/question_index/1')),
    path('admin/', admin.site.urls),
    url(r'^account/', include('AccountApp.urls', namespace='account')),
    url(r'^question/', include('QuestionApp.urls', namespace='question')),
    url(r'^answer/', include('AnswerApp.urls', namespace='answer')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('tree/', include('tree.urls', namespace='tree')),
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'mdeditor/', include('mdeditor.urls')),

]

QuestionApp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import url
from . import views
from tree.views import node_detail

app_name = 'question'

urlpatterns = [
    path('question_index/<int:page_id>/', views.index, name='index'),
    path('<int:question_id>/', views.question_content, name="question_content"),
    path('<int:question_id>/node/<int:node_id>', node_detail,name='node'),
    path('add_question/', views.ask, name='add_question'),
    path('search/', views.search, name='search'),
    path('show_question/', views.questionContent, name='questionContent'),
    path('like-question/', views.like_question, name="like_question"),
    path('like/<int:id>/<str:action>/', views.like_question, name='like_question'),
    path('unlike/<int:id>/<str:action>/', views.like_question, name='like_question'),
    path('my_questions/', views.my_questions, name='my_questions'),
    path('redit-question/<int:question_id>/', views.redit_question, name="redit_question"),
    path('collect/<int:id>/<str:action>/', views.collect, name='collect_question'),
    path('collect/<int:id>/<str:action>/', views.collect, name='cancel_collect_question'),
    path('delete-question/<int:question_id>/', views.delete_question, name="delete_question"),
    path('my_center/',views.my_center,name='my_center'),
    path('my_answers/',views.my_answers,name='my_answers'),
    path('upload/',views.upload,name='upload'),
    path('delete-question/<int:question_id>',views.deletequestion, name='delete-question'),
]

tree/urls.py
from django.urls import path
from . import views

app_name = 'tree'

urlpatterns = [

    path('create/', views.create, name='create-tree-url'),
    path('delete/', views.delete, name='delete-tree-url'),
    path('node/<department_id>/', views.node_detail,name='node'),
    path('node/<int:department_id>/modify/', views.modify_post, name='modify'),
    path('node/<int:department_id>/modify/uploadFile/', views.upload_file, name='uploadFile'),#上传文件
    path('node/<int:department_id>/modify/deleteFile/<int:pk>', views.delete_file, name='delete_file'),#删除文件
    path('node/<int:department_id>/download_file/<int:pk>/',views.download_file,name='download_file'),#下载文件

    ]

QuestionApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Question, Category
import re


class AskForm(forms.Form):
    """
    class Meta:
         model = Question
         fields=('questionTitle', 'category', 'questionDescription')

    """
    category = forms.ChoiceField(choices=Category.objects.values_list('number', 'name'), required=True, widget=forms.RadioSelect)
    title = forms.CharField(label='请输入问题题目(60字以内):', max_length=60,required=True, widget=forms.TextInput(attrs={"class":"form-control"}))
    #question = forms.CharField(label='请输入问题内容(2000字以内):', max_length=2000, required=True,widget=forms.Textarea(attrs={"class":"form-control"}))
    
    def clean_category(self):
        category = self.cleaned_data.get('category')
        return category

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 3:
            raise forms.ValidationError("Your title must be at least 3 characters long.")
        elif len(title) > 60:
            raise forms.ValidationError("Your title is too long.")
        else:
            filter_result = Question.objects.filter(questionTitle__exact=title)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your title already exists.")
        return title
    """
    def clean_question(self):
        question = self.cleaned_data.get('question')

        if len(question) < 3:
            raise forms.ValidationError("Your text must be at least 3 characters long.")
        elif len(question) > 2000:
            raise forms.ValidationError("Your text is too long.")
        else:
            return question
    """

templates/question/add_question.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="col-sm-9">
    <div class="tt-topic-list">
        <div class="tt-list-header">
            <div class="tt-col-topic">
                <h2>Add Database</h2>
            </div>
        </div>
    </div>
        <div id="fh5co-contact" >
            <div class="container">
                <form action="." method="post">
                    {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.category.id_for_label }}">请选择数据集🌲&nbsp;&nbsp;类型</label>
                    {{ form.category }}
                </div>
                <div class="form-group">
                    <label for="{{ form.title.id_for_label }}">名称</label>
                    {{ form.title }}
                </div>
                    <div class="miaoshu"><span>详细描述：</span></div>
                    <div class="row" style="margin-top: 10px;">
                    <div id="editormd" class="col-md-10 text-left">
                    <textarea style="display: none;" id="id_body"></textarea>
                </div>
                    </div>
            </div>
                    <div class="row text-center vertical-middle-sm" >
                        {{ askMessage }}
                        <button type="submit" class="btn btn-default btn-lg" style="margin-left:200px">提交</button>
                    </div>
                </form>
            </div>
        </div>
</div>

<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript" src="{% static "js/csrf.js" %}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
<script type="text/javascript">
    function add_question() {
        var questionTitle = $("#id_title").val();
        var category_id = $("#which_category").val();
        var body = $("#id_body").val();
        $.ajax({
            url:"{% url 'question:add_question' %}",
            type:"POST",
            data: {"questionTitle":questionTitle,"questionDescription":body,"category":category_id},
            success:function (e) {
                    if(e==="1")
                        layer.msg("successful");
                    else if(e===2)
                        layer.msg("sorry");
                    else {
                        layer.msg("sorry2");

                    }

            }

        })

    }
</script>

        <!--markdown-->
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
    $(function() {
        var editor  = editormd("editormd",{
            width : "100%",
            height : 640,
            path : "{% static 'editor/lib/' %}",
            syncScrolling : "single",
            tocm: true,         // Using [TOCM]
                    tex: true,                   // 开启科学公式TeX语言支持，默认关闭
                    flowChart: true,             // 开启流程图支持，默认关闭
                    sequenceDiagram: true,       // 开启时序/序列图支持，默认关闭,
                    imageUpload: true,
                    imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                    imageUploadURL: "{% url 'question:upload' %}",
                    onload: function () {
                        console.log('onload', this);
                    },
        });
    });
</script>
{% endblock %}
{% block right %}
<div class="col-sm-3" >
    <div class="side-bar-well clearfix" style="position: fixed;">
        <div class="col-sm-5"><img src="{% static 'images/support.png' %}"></div>
        <div class="col-sm-7">
{% if user.username %}
            <p class="side-bar-well-title">{{user.username}}</p>
            <p>🟢&nbsp;&nbsp;&nbsp;正在登录</p>
            {% else %}
            <p>🔴&nbsp;&nbsp;&nbsp;未登录</p>
            {% endif %}
        </div>
    </div>
    <div class="side-bar-well" style="position: fixed;margin-top:90px">
        <strong class="side-bar-well-title">常访问数据集：</strong>
        {% for question in question_2 %}
        <a href="{% url 'question:question_content' question_id=question.id %}" class="news-item">
            <div class="news-title">{{question.questionTitle}}</div>
        </a>
        <div class="news-info">
            <span>{{ question.user }}</span>
            <span>&nbsp{{question.created}}&nbsp</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/question/content.html
{% extends "./index_question.html" %}
{% load markdown_extras %}
{% load static %}

{% block content %}
<div class="col-sm-9">
    <div class="tt-single-topic-list">
        <div class="tt-item">
            <div class="tt-single-topic">
                <div class="tt-item-header">
                    <div class="tt-item-info info-top">
                        <div class="tt-avater-title">
                            <a href="#">{{ question.user }}</a>
                        </div>
                        <a href="#" class="tt-info-time">
                            <i class="tt-icon"><svg>
                                    <use xlink:href="#icon-time"></use>
                                </svg></i>{{timezone.now}}
                        </a>
                    </div>
                    <h1 class="tt-item-title">
                        <h2>{{ question.questionTitle }}</h2>
                    </h1>
                    <div class="tt-item-tag">
                        <ul class="tt-list-badge">
                            <li><a href="#"><span class="tt-color07 tt-badge">{{ question.questionCategory }}</span></a>
                            </li>
                            <li><a href="#"><span class="tt-color09 tt-badge">{{ question.created }}</span></a>
                            </li>
                        </ul>
                    </div>
<!--                    <div class="tt-item-tag">-->
<!--                        <ul class="tt-list-badge">-->
<!--                            {% if question_collect %}-->
<!--                            <li><a href="{% url 'question:cancel_collect_question' id=question.id action='取消收藏' %}">-->
<!--                                    <span class="tt-badge">取消收藏</span></a></li>-->
<!--                            {% else %}-->
<!--                            <li><a href="{% url 'question:collect_question' id=question.id action='收藏' %}">-->
<!--                                    <span class="tt-badge">⭐&nbsp;&nbsp;&nbsp;收藏</span></a></li>-->
<!--                            {% endif %}-->
<!--                         <li><a  href="#"><span class="tt-badge"> {{ question.views }}view{{ question.views|pluralize }}-->
<!--                                    </span></a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
                </div>
                <div class="tt-item-description">
                    <h3>试验数据描述：</h3>
                    <p>{{ question.questionDescription | markdown | safe }}</p>

                    {% include 'tree/tree.html'  %}
                </div>
                {% block node %}
            </div>
        </div>
        {% endblock node %}
    </div>
</div>
{% endblock content %}
{% block page %}{% endblock %}
{% block right %}
<div class="col-sm-3" >
    <div class="side-bar-well clearfix" style="position: fixed;">
        <div class="col-sm-5"><img src="{% static 'images/support.png' %}"></div>
        <div class="col-sm-7">
            {% if user.username %}
            <p class="side-bar-well-title">{{user.username}}</p>
            <p>🟢&nbsp;&nbsp;&nbsp;正在登录</p>
            {% else %}
            <p>🔴&nbsp;&nbsp;&nbsp;未登录</p>
            {% endif %}
        </div>
    </div>
    <div class="side-bar-well" style="position: fixed; margin-top:90px">
        <strong class="side-bar-well-title">常访问数据集</strong>
        {% for question in question_2 %}
        <a href="{% url 'question:question_content' question_id=question.id %}" class="news-item">
            <div class="news-title">{{question.questionTitle}}</div>
        </a>
        <div class="news-info">
            <span>{{ question.user }}</span>
            <span>&nbsp{{question.created}}&nbsp</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript" src="{% static "js/csrf.js" %}"></script>
<script>
    function like_question(id, action) {
        $.ajax(
            {
                url: "{% url 'question:like_question' %}",
                type: "POST",
                data: { "id": id, "action": action },
                success: function (e) {
                    if (e === 1) {
                        layer.msg("感谢点赞");
                        window.location.reload();

                    } else {
                        layer.msg("我会继续努力");
                        window.location.reload();
                    }

                },
                error: function (e) {
                    layer.msg("发送失败");

                }
            });

    }
</script>

templates/question/content_node.html
{% extends "question/content.html" %}
{% load markdown_extras %}
{% load static %}

{% block node %}
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
    showProcessingMessages: false, //关闭js加载过程信息
    messageStyle: "none", //不显示信息
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
        inlineMath:  [['$', '$']], //行内公式选择$
        displayMath: [ ["$$","$$"] ], //段内公式选择$$
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code','a'], //避开某些标签
        ignoreClass:"comment-content" //避开含该Class的标签
    },
    "HTML-CSS": {
        availableFonts: ["STIX","TeX"], //可选字体
        showMathMenu: true //关闭右击菜单显示
    }
    });
    MathJax.Hub.Queue(["Typeset",MathJax.Hub]);

    </script>
    <script src="//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <link rel="dns-prefetch" href="//cdn.mathjax.org" />


    <style>
        p{
            font-family:&amp;quot;Microsoft YaHei&amp;quot;,微软雅黑,&amp;quot;MicrosoftJhengHei&amp;quot;,华文细黑,STHeiti,MingLiu; /*若电脑不支持宋体，则用仿宋，若不支持仿宋，则在sans-serif中找*/
            line-height:0px;
            //margin:0 auto;
            //font-weight: bold;
            font-size: 120%;
            //font-style: italic;
            //color: red;/*字体颜色*/
            //opacity: 0.5;/*字体的透明度：1：默认样式，0：全透明*/
        }
        div{
            font-family:&amp;quot;Microsoft YaHei&amp;quot;,微软雅黑,&amp;quot;MicrosoftJhengHei&amp;quot;,华文细黑,STHeiti,MingLiu;
            }
    </style>

<h4>{{department.name}}</h4>
    <div class="entry-meta">
      <span class="post-date"><a href="#"><time class="entry-date"
                                                datetime="{{ node.created_time }}">{{ node.created_time }}</time></a></span>
      <span class="post-author">作者: &nbsp;{{ node.author }}</span>

&nbsp;&nbsp;&nbsp;&nbsp;
{% if user.is_superuser %}
<a href="modify/"><span class="tt-badge">修改</span></a>
{% endif %}
    </div>
{% for nodefile in nodefile %}
{% if nodefile.pk %}
<!--下载-->
<div>
<a href="{% url  'tree:download_file' department_id=nodefile.department_id pk=nodefile.pk %}" style="color : cornflowerblue; font-size: 15px">{{nodefile.File_name}}  &nbsp; 下载 </a>
    {% if user.is_superuser %}
<a href="{% url  'tree:delete_file' department_id=nodefile.department_id pk=nodefile.pk %}" style="color : orangered; font-size: 15px"> &nbsp;&nbsp; 删除 </a>
    {% endif %}
</div>
{% endif %}
{% endfor %}
<article class=" post-{{ node.pk }}">
<!--  <div class="entry-content clearfix">-->
    <div>
    <br />

   {{ node.body| markdown | safe }}
  </div>
</article>

<!--<script>-->
<!--    $(function(){undefined-->
<!--  $("p").text("p标签内容");-->
<!--})-->
<!--</script>-->
{% endblock node %}
{% block right%}
{% endblock %}



templates/question/index_question.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <style>
        div{
            font-family:&amp;quot;Microsoft YaHei&amp;quot;,微软雅黑,&amp;quot;MicrosoftJhengHei&amp;quot;,华文细黑,STHeiti,MingLiu;
            }
    </style>
</head>

<body>
    {% include "head.html" %}
    <main id="tt-pageContent" class="tt-offset-small">
        <div class="blank">
            <p>&nbsp</p>
        </div>
        <div class="container">
            {% block title %}{% endblock %}
            {% block register %}
            <div class="row">
            {% block content %}
                <div class="col-sm-2">
                    <div class="side-bar" style="position: fixed;">
                        <a class="list-group-item" href="{% url 'question:index' page_id=1 %}">全部&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
                        {% for category in categorys %}
                        <a class="list-group-item" href="/question/question_index/1/?category_id={{ category.id }}">{{ category.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="tt-topic-list">
                        <div class="tt-list-header">
                            <div class="tt-col-topic">
                                <h2>试验数据管理</h2>
                            </div>
                        </div>
                        {% block question_list %}{% endblock %}
                        {% with total_likes=question.users_like.count  users_like=question.users_like.all %}
                        {% for question in page_of_questions %}
                        <div class="tt-item">
                            <div class="tt-row-descrption">
                                <h4 class="tt-title"><a href="{% url 'question:question_content' question_id=question.id %}">
                                        {{question.questionTitle}}
                                </a></h4>
                                <div class="row align-items-center no-gutters">

                                    <div class="col-1 ml-auto show-mobile">
                                        <div class="tt-value">1d</div>
                                    </div>
                                </div> 
                            </div>
                            <div class="tt-col-category"><span
                                    class="tt-color04 tt-badge">{{ question.questionCategory }}</span></div>
                            <div class="col-ms-3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ question.user }}发表于{{ question.created | date:'Y年m月d日 h时 i分' }}</div>
                            {% if user.is_superuser %}
                            <a href="{% url 'question:delete-question' question_id=question.pk  %}?page_id=1"><div class="news-title">&nbsp;&nbsp;&nbsp;&nbsp;删除</div></a>
                            {% endif %}
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                {% endblock %}
                {% block right %}
                <div class="col-sm-3" >
                    <div class="side-bar-well clearfix" style="position: fixed;">
                        <div class="col-sm-5"><img src="{% static 'images/support.png' %}"></div>
                        <div class="col-sm-7">

                            {% if user.username %}
                            <p class="side-bar-well-title">{{user.username}}</p>
                            <p>🟢&nbsp;&nbsp;&nbsp;正在登录</p>
                            {% else %}
                            <p>🔴&nbsp;&nbsp;&nbsp;未登录</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="side-bar-well" style="position: fixed; margin-top:90px">
                        <strong class="side-bar-well-title">常访问数据集：</strong>
                        {% for question in question_2 %}
                        <a href="{% url 'question:question_content' question_id=question.id %}" class="news-item">
                            <div class="news-title">{{question.questionTitle}}</div>
                        </a>
                        <div class="news-info">
                            <span>{{ question.user }}</span>
                            <span>&nbsp{{question.created}}&nbsp</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endblock right %}
                {% endblock %}
            </div>
       
        </div>
        {% block page %}
         <div class="text-center">
            <ul class="pagination" >
            <li>
                {# 上一页 #}
                {% if page_of_questions.has_previous %}
                    <a href="{% url 'question:index' page_id=page_of_questions.previous_page_number %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% else %}
                    <span aria-hidden="true">&laquo;</span>
                {% endif %}
            </li>
                {# 页码 #}
                {% for page_num in page_range %}
                    {% if page_num == page_of_questions.number %}
                        <li class="active"><a href="{% url 'question:index' page_id=page_num %}">{{ page_num }}</a></li>
                    {% else %}
                        {% if page_num == '...' %}
                            <li><span>{{ page_num }}</span></li>
                        {% else %}
                            <li><a href="{% url 'question:index' page_id=page_num %}">{{ page_num }}</a></li>
                        {% endif %}

                    {% endif %}
                {% endfor %}
            <li>
                {# 下一页 #}
                {% if page_of_questions.has_next %}
                    <a href="{% url 'question:index' page_id=page_of_questions.next_page_number %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                 {% else %}
                    <span aria-hidden="true">&raquo;</span>
                 {% endif %}
            </li>
            </ul>
            </div>
        {% endblock %}
    
    </main>
    {% block javascript %}{% endblock %}
</body>

</html>

templates/question/my_questions.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<div class="col-sm-9">
    <main id="tt-pageContent" class="tt-offset-small">
        <div class="container">
            <div class="tt-topic-list">
                <div class="tt-list-header">
                    <div class="tt-col-topic text-center">
                        <h1>我的问题</h1>
                        <p>点击查看详细</p>
                    </div>
                </div>
                {% for question in questions %}
                <div class="tt-item">
                    <div class="tt-single-topic">
                        <div class="tt-item-header pt-noborder">
                            <div class="tt-item-header info-top">
                                <div class="tt-avater-title">
                                    <a href="#">author: {{ question.user }}</a>
                                </div>
                                <div class="tt-item-title">
                                    <a href="../{{question.id}}">{{question.questionTitle}}</a>
                                </div>
                                <div class="tt-item-tag">
                                    <ul class="tt-list-badge">
                                        <li><a href="#"><span
                                                    class="tt-color09 tt-badge">发表于{{ question.created }}</span></a></li>
                                        <li><a href="#"><span class="tt-color02 tt-badge">赞同 {{ question.goodNum }}</span></a></li>
                                        <li><a href="#"><span class="tt-color02 tt-badge">反对 {{ question.badNum }}</span></a></li>
                                        <li><a href="{%  url 'question:redit_question' question_id=question.id %}"><span class="tt-badge">修改问题</span> </a> </li>
                                        <li><a href="{%  url 'question:delete_question' question_id=question.id %}"><span class="tt-badge">删除问题</span> </a> </li>
                                    </ul>
                                </div>
                                <div class="tt-item-title">
                                    <p>{{ question.questionDescription | truncatechars:"30"}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            <div class="tt-list-header">
                    <div class="tt-col-topic text-center">
                        <h1>我的回答</h1>
                        <p>点击查看详细</p>
                    </div>
                </div>
                {% for answer in answers %}
                <div class="tt-item">
                    <div class="tt-single-topic">
                        <div class="tt-item-header pt-noborder">
                            <div class="tt-item-header info-top">
                                <div class="tt-avater-title">
                                    <a href="#">author: {{ answer.author }}</a>
                                </div>
                                <div class="tt-item-title">
                                    <a href="../{{answer.question.id}}">{{answer.question.questionTitle}}</a>
                                </div>
                                <div class="tt-item-tag">
                                    <ul class="tt-list-badge">
                                        <li><a href="#"><span
                                                    class="tt-color09 tt-badge">发表于{{ answer.pub_date }}</span></a></li>
                                        <li><a href="#"><span class="tt-color02 tt-badge">赞同 {{ answer.goodNum }}</span></a></li>
                                        <li><a href="#"><span class="tt-color02 tt-badge">反对 {{ answer.badNum }}</span></a></li>
                                    </ul>
                                </div>
                                <div class="tt-item-title">
                                    <p>{{ answer.answer_text | truncatechars:"30"}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
</div>
{% endblock %}


templates/question/redit_question.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
</head>
<body>
<div class="container">
    {#    导航栏#}
    {% include "head.html" %}
    {% block add_question %}
    {% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div>
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 100px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{question_form.title}}</div>
        </div>

        <div  class="row" style="margin-top: 10px;">
        	<div class="col-md-2 text-right"><span>内容:</span></div>
        	<div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none;" id="id_body">
{{question.questionDescription}}
                </textarea>
        	</div>
        </div>
        <div class="row">
            <input type="submit" class="btn btn-primary btn-lg" value="发布" >
        </div>
    </form>

</div>
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
            width   : "100%",
            height  : 640,
            path    : "{% static 'editor/lib/' %}",
        });
    });

function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'question:redit_question' question.id %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id},
        success: function(e){
            if(e=="1"){
                layer.msg("successful");

            }else{
        	layer.msg("sorry.");
            }
        },
    });
}

</script>

    {% endblock %}
	{% endblock %}


</div>

</body>
</html>