AccountApp/urls.py
from django.conf.urls import url
from .import views

from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'AccountApp'

urlpatterns = [
    url('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name="user_login"),
    url("new-login/", auth_views.LoginView.as_view, {"template_name": "account/login.html"}),
    url('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name="user_logout"),
    url("logout/", auth_views.LoginView.as_view, {"template_name": "account/logout.html"}, name="user_logout"),
    url(r'^register/$', views.register, name="user_register"),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html'),
         {"post_change_redirect": "account/password-change-done"}, name='password_change'),
    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
         name='account/password_change_done'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html", success_url=reverse_lazy('account:password_reset_done'),
        email_template_name='account/password_reset_email.html', subject_template_name='account/password_reset_subject.txt'),  name="password_reset"),
    url(r'^password-reset-done/$', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),
        name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url=reverse_lazy('account:password_reset_complete')),
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
        name="password_reset_complete"),

    url(r'^my-information/$', views.myself, name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
    url(r'^my-collections/$', views.my_collect, name="my_collections")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LearningShare/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url, include
from django.views.generic import RedirectView
from tree.views import create
from . import settings
from django.views.static import serve

urlpatterns = [
    path('', RedirectView.as_view(url='question/question_index/1')),
    path('admin/', admin.site.urls),
    url(r'^account/', include('AccountApp.urls', namespace='account')),
    url(r'^question/', include('QuestionApp.urls', namespace='question')),
    url(r'^answer/', include('AnswerApp.urls', namespace='answer')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('tree/', include('tree.urls', namespace='tree')),
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'mdeditor/', include('mdeditor.urls')),

]

QuestionApp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import url
from . import views
from tree.views import node_detail

app_name = 'question'

urlpatterns = [
    path('question_index/<int:page_id>/', views.index, name='index'),
    path('<int:question_id>/', views.question_content, name="question_content"),
    path('<int:question_id>/node/<int:node_id>', node_detail,name='node'),
    path('add_question/', views.ask, name='add_question'),
    path('search/', views.search, name='search'),
    path('show_question/', views.questionContent, name='questionContent'),
    path('like-question/', views.like_question, name="like_question"),
    path('like/<int:id>/<str:action>/', views.like_question, name='like_question'),
    path('unlike/<int:id>/<str:action>/', views.like_question, name='like_question'),
    path('my_questions/', views.my_questions, name='my_questions'),
    path('redit-question/<int:question_id>/', views.redit_question, name="redit_question"),
    path('collect/<int:id>/<str:action>/', views.collect, name='collect_question'),
    path('collect/<int:id>/<str:action>/', views.collect, name='cancel_collect_question'),
    path('delete-question/<int:question_id>/', views.delete_question, name="delete_question"),
    path('my_center/',views.my_center,name='my_center'),
    path('my_answers/',views.my_answers,name='my_answers'),
    path('upload/',views.upload,name='upload'),
    path('delete-question/<int:question_id>',views.deletequestion, name='delete-question'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

tree/urls.py
from django.urls import path
from . import views

app_name = 'tree'

urlpatterns = [

    path('create/', views.create, name='create-tree-url'),
    path('delete/', views.delete, name='delete-tree-url'),
    path('node/<department_id>/', views.node_detail,name='node'),
    path('node/<int:department_id>/modify/', views.modify_post, name='modify'),
    path('node/<int:department_id>/modify/uploadFile/', views.upload_file, name='uploadFile'),#上传文件
    path('node/<int:department_id>/modify/deleteFile/<int:pk>', views.delete_file, name='delete_file'),#删除文件
    path('node/<int:department_id>/download_file/<int:pk>/',views.download_file,name='download_file'),#下载文件

    ]

QuestionApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Question, Category
import re


class AskForm(forms.Form):
    """
    class Meta:
         model = Question
         fields=('questionTitle', 'category', 'questionDescription')

    """
    category = forms.ChoiceField(choices=Category.objects.values_list('number', 'name'), required=True, widget=forms.RadioSelect)
    title = forms.CharField(label='请输入问题题目(60字以内):', max_length=60,required=True, widget=forms.TextInput(attrs={"class":"form-control"}))
    #question = forms.CharField(label='请输入问题内容(2000字以内):', max_length=2000, required=True,widget=forms.Textarea(attrs={"class":"form-control"}))
    
    def clean_category(self):
        category = self.cleaned_data.get('category')
        return category

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 3:
            raise forms.ValidationError("Your title must be at least 3 characters long.")
        elif len(title) > 60:
            raise forms.ValidationError("Your title is too long.")
        else:
            filter_result = Question.objects.filter(questionTitle__exact=title)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your title already exists.")
        return title
    """
    def clean_question(self):
        question = self.cleaned_data.get('question')

        if len(question) < 3:
            raise forms.ValidationError("Your text must be at least 3 characters long.")
        elif len(question) > 2000:
            raise forms.ValidationError("Your text is too long.")
        else:
            return question
    """

templates/head.html
{% load static %}
<!-- 引入notifications的模板标签 -->
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DataForest</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        div{
            font-family:&amp;quot;Microsoft YaHei&amp;quot;,微软雅黑,&amp;quot;MicrosoftJhengHei&amp;quot;,华文细黑,STHeiti,MingLiu;
            }
    </style>
</head>

<body>
    <header id="tt-header">
        <div class="container">
            <div class="row tt-row no-gutters">
                <div class="col-auto">

                    <a class="toggle-mobile-menu" href="#">
                        <svg class="tt-icon">
                        </svg>
                    </a>
                    <!-- /toggle mobile menu -->
                    <!-- logo -->
                    <div class="tt-logo">
                        <a href="{% url 'question:index' page_id=1  %}"><img src="{% static 'images/IMG_0212.JPG' %}" alt=""></a>
                    </div>


                    <div class="tt-title">
                        <a href="{% url 'question:index' page_id=1 %}"><span style="font-size:23px">DataForest</span></a>
                    </div>

                    <!-- menu -->
                    {% if user.is_superuser %}
                    <div class="tt-desktop-menu">
                        <nav>
                            <ul>
                                <!-- <li><a href="{% url 'question:index' page_id=1 %}"><span>LearningShare</span></a></li> -->
<!--                                <li><a href="{% url 'question:index' page_id=1 %}"><span style="font-size:20px">主页</span></a></li>-->
                                <li><a href="{% url 'question:add_question' %}"><span style="font-size:20px">添加数据集</span></a></li>
                            </ul>
                        </nav>
                    </div>
                    {% else %}
                    <div class="tt-desktop-menu">
                        <nav>
                            <ul>
                                <!-- <li><a href="{% url 'question:index' page_id=1 %}"><span>LearningShare</span></a></li> -->
<!--                                <li><a href="{% url 'question:index' page_id=1 %}"><span style="font-size:20px">主页</span></a></li>-->
                                <li><span style="font-size:20px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></li>
                            </ul>
                        </nav>
                    </div>
{% endif %}
                    <!-- search -->
                    <div class="tt-search">
                        <!-- toggle -->
                        <button class="tt-search-toggle" data-toggle="modal" data-target="#modalAdvancedSearch">
                        </button>

                        <form class="search-wrapper" role="search" method="get" action="{%url 'question:search' %}">
                            <div class="form-group">
                                <input type="search" class="tt-search__input" name="keyword" placeholder="Search"
                                    required>
                                <!-- <button type="submit" class="btn btn-default"><span>搜索</span></button> -->
                                <!-- <button type="button" class="tt-view-all" data-toggle="modal" data-target="#modalAdvancedSearch">Advanced Search</button> -->
                            </div>
                        </form>
                    </div>

                    <div class="tt-desktop-menu">
                        <nav>
                            <ul>
                                <p>&nbsp&nbsp&nbsp&nbsp</p>
                            </ul>
                        </nav>
                    </div>

                    <div class="col-auto">
                        <div class="tt-account-btn">
                            <a href="{% url 'account:user_register' %}" class="btn btn-secondary"><span>注册</span></a>
                        </div>
                    </div>

                    <div class="tt-desktop-menu">
                        <nav>
                            <ul>
                                    {% if user.is_authenticated %}
                                    <li>

                                        <a href="#">
                                            <!-- 新增代码，小红点 -->
                                            {% if unread_count %}
                                                <svg viewBox="0 0 8 8"
                                                     width="8px"
                                                     height="8px">
                                                    <circle cx="4"
                                                            cy="4"
                                                            r="4"
                                                            fill="#ff6b6b"
                                                            ></circle>
                                                </svg>
                                            {% endif %}
                                            <span>
                                            {% if user.userinfo.photo %}
                                            <img src="{{ user.userinfo.photo | striptags }}" height="40" width="40"
                                                 class="img-circle" id="my_photo" name="user_face">
                                            {% else %}
                                            <img name="user_face" src="{% static 'images/default.jpg' %}" height="35" width="35"
                                                 class="img-circle" width="270px" id="my_photo">
                                            {% endif %}
                                            </span>
                                            </a>
                                        <ul>
                                            <li><a href="{% url 'question:my_center' %}">我的主页</a></li>
                                            <li><a href="{% url 'notice:list' %}">通知
                                                {% if unread_count %}
                                                <span class="badge badge-danger" >{{ unread_count }}</span>
                                                {% endif %}
                                            </a> </li>
                                            <!--<li><a href="{% url 'account:password_change' %}">修改密码</a></li>-->
                                            <li><a href="{% url 'account:user_logout' %}">退出</a></li>
                                        </ul>
                                    {% else %}
                                    <li>
                                        <a href="{% url 'account:user_login' %}" style="font-size:20px">登录</a>
                                    </li>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </header>
</body>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <style>
        div{
            font-family:&amp;quot;Microsoft YaHei&amp;quot;,微软雅黑,&amp;quot;MicrosoftJhengHei&amp;quot;,华文细黑,STHeiti,MingLiu;
            }
    </style>
</head>

<body>
    {% include "head.html" %}
    <main id="tt-pageContent" class="tt-offset-small">
        <div class="blank">
            <p>&nbsp</p>
        </div>
        <div class="container">
            {% block title %}{% endblock %}
            {% block register %}
            <div class="row">
            {% block content %}
                <div class="col-sm-2">
                    <div class="side-bar">
                        <a class="list-group-item" href="{% url 'question:index' page_id=1 %}">全部</a>
                        {% for category in categorys %}
                        <a class="list-group-item" href="/question/?category_id={{ category.id }}">{{ category.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="tt-topic-list">
                        <div class="tt-list-header">
                            <div class="tt-col-topic">
                                <h2>Question List</h2>
                            </div>
                        </div>
                        {% block question_list %}{% endblock %}
                        {% with total_likes=question.users_like.count  users_like=question.users_like.all %}
                        {% for question in question_1 %}
                        <div class="tt-item">
                            <div class="tt-row-descrption">
                                <h4 class="tt-title"><a href="{{ question.id }}">
                                        {{question.questionTitle}}
                                </a></h4>
                                <div class="row align-items-center no-gutters">
                                    <div class="col-11">
                                        <ul class="tt-list-badge">
                                            <li><a href="#"><span class="tt-badge">赞同 {{ question.users_like.count }}</span></a></li>
                                        </ul>
                                    </div>
                                    <div class="col-1 ml-auto show-mobile">
                                        <div class="tt-value">1d</div>
                                    </div>
                                </div> 
                            </div>
                            <div class="tt-col-category"><span
                                    class="tt-color04 tt-badge">{{ question.questionCategory }}</span></div>

                            <div class="col-ms-3">{{ question.user }}发表于{{ question.created }}</div>
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                {% endblock %}
                {% block left %}
       <div class="col-sm-3" >
                    <div class="side-bar-well clearfix" style="position: fixed;">
                        <div class="col-sm-5"><img src="{% static 'images/support.png' %}"></div>
                        <div class="col-sm-7">

                            {% if user.username %}
                            <p class="side-bar-well-title">{{user.username}}</p>
                            <p>🟢&nbsp;&nbsp;&nbsp;正在登录</p>
                            {% else %}
                            <p>🔴&nbsp;&nbsp;&nbsp;未登录</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="side-bar-well" style="position: fixed; margin-top:90px">
                        <strong class="side-bar-well-title">常访问数据集：</strong>
                        {% for question in question_2 %}
                        <a href="{% url 'question:question_content' question_id=question.id %}" class="news-item">
                            <div class="news-title">{{question.questionTitle}}</div>
                        </a>
                        <div class="news-info">
                            <span>{{ question.user }}</span>
                            <span>&nbsp{{question.created}}&nbsp</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endblock %}
                {% endblock %}
            </div>
       
        </div>
    
    </main>

    {% block javascript %}{% endblock %}
</body>

</html>

templates/test.html
<div style="margin-left: 10px">

    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div id="id_title" class="col-md-2 text-right"><span>问题：</span></div>
            <input class="col-md-10 text-left" type="text">{{ form.questionTitle }}</input>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>类型：</span></div>
            <div class="col-md-10 text-left">
                <select id="which_category">
                    {% for category in category %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            {{ form.category }}
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>详细描述：</span></div>
                        <!--<div class="col-md-10 text-left">{{ form.question }}</div>-->
            {{ form.question }}
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display: none;" id="id_body"></textarea>
            </div>
        </div>
        <div class="row">
 {#           <input  type="button" class="btn btn-default"  value="提问2" onclick="add_question()">#}
            <button type="submit" class="btn btn-default" value="提交"></button>
        </div>
    </form>
</div>